#!/bin/bash

# If you decide to move this script to somewhere else, then you can set the
# environment variable EMUSICJ_HOME to point to where the program actually is.
PROGRAM_DIR="$EMUSICJ_HOME"

# This function taken from Azureus, and modified
check_version()
{
  JAVA_HEADER=`java -version 2>&1 | head -n 1`
  JAVA_IMPL=`echo ${JAVA_HEADER} | cut -f1 -d' '`
  if [ "$JAVA_IMPL" = "java" ] ; then
    VERSION=`echo ${JAVA_HEADER} | sed "s/java version \"\(.*\)\"/\1/"`
    if echo $VERSION | grep "^1.[0-4]" ; then
      echo Your Java version is too old "[java = ${VERSION}]"
      echo You need to upgrade to Java 1.5 or higher.
      echo See http://www.kallisti.net.nz/EMusicJ/InstallingJava for details.
      exit 1
    else
      return 0
    fi
  else
    echo You don\'t seem to have a valid JRE "[java = ${JAVA_IMPL}]" 
    echo See http://www.kallisti.net.nz/EMusicJ/InstallingJava for details.
    exit 1
  fi
}


if [ -z "$PROGRAM_DIR" ]; then
    PROGRAM_DIR=`dirname "$0"`
    PROGRAM_DIR=`cd "$PROGRAM_DIR"; pwd`
else
    if [ "$(echo ${PROGRAM_DIR}/lib/*.jar)" = "${PROGRAM_DIR}/lib/*.jar" ]; then
        echo "You seem to have set an invalid PROGRAM_DIR, unable to continue!"
        exit 1
    elif ! (echo ${PROGRAM_DIR}/lib/*.jar | grep classicsonline.jar >/dev/null 2>&1 ); then
        echo "Unable to locate classicsonline.jar in $PROGRAM_DIR, aborting!"
        exit 1
    fi
fi
MACHINE=`uname -m`

check_version

# swt.jar is referenced twice because it is in a different place on a 
# checked-out tree versus a dist build
MY_CLASSPATH="${PROGRAM_DIR}/lib/${MACHINE}/swt.jar:${PROGRAM_DIR}/lib/swt.jar:${PROGRAM_DIR}/lib/commons-codec-1.3.jar:${PROGRAM_DIR}/lib/commons-httpclient-3.0-rc4.jar:${PROGRAM_DIR}/lib/commons-logging-api.jar:${PROGRAM_DIR}/lib/retroweaver-rt-1.2.4.jar:${PROGRAM_DIR}/lib/guice-1.0.jar:${PROGRAM_DIR}/lib/MRJAdapter.jar:${PROGRAM_DIR}/lib/JID3.jar:$CLASSPATH"

if [ -e ${PROGRAM_DIR}/bin/nz/net/kallisti/emusicj/ClassicsOnline.class ] ; then
        java -cp "${PROGRAM_DIR}/bin:$MY_CLASSPATH" "-Djava.library.path=${PROGRAM_DIR}/lib/${MACHINE}" -Denv.http_proxy=${http_proxy} nz.net.kallisti.emusicj.ClassicsOnline $@
elif [ -e ${PROGRAM_DIR}/lib/classicsonline.jar ] ; then
	java -cp "${PROGRAM_DIR}/lib/classicsonline.jar:$MY_CLASSPATH" "-Djava.library.path=${PROGRAM_DIR}/lib" -Denv.http_proxy=${http_proxy} nz.net.kallisti.emusicj.ClassicsOnline $@
else
        echo "Couldn't find the compiled Java program.";
fi

