#!/bin/bash
MY_CLASSPATH=lib/swt.jar:lib/commons-codec-1.3.jar:commons-httpclient-3.0-rc4.jar:commons-logging-api.jar:$CLASSPATH
if [ -e emusicj.jar ] ; then
	java -cp $MY_CLASSPATH -Djava.library.path=lib -jar emusicj.jar ;
elif [ -e bin/nz/net/kallisti/emusicj/EMusicJ.class ] ; then
	java -cp bin:$MY_CLASSPATH -Djava.library.path=lib nz/net/kallisti/emusicj/EMusicJ
else
	echo "Couldn't find the compiled Java program.";
fi
