#!/bin/bash

# If you decide to move this script to somewhere else, then you can set the
# environment variable PASSIONATO_HOME to point to where the program actually is.
PROGRAM_DIR="$PASSIONATO_HOME"

# This function taken from Azureus, and modified
check_version()
{
  JAVA_HEADER=`java -version 2>&1 | head -n 1`
  JAVA_IMPL=`echo ${JAVA_HEADER} | cut -f1 -d' '`
  if [ "$JAVA_IMPL" = "java" ] ; then
    VERSION=`echo ${JAVA_HEADER} | sed "s/java version \"\(.*\)\"/\1/"`
    if echo $VERSION | grep "^1.[0-4]" ; then
      echo Your Java version is too old "[java = ${VERSION}]"
      echo You need to upgrade to Java 1.5 or higher.
      echo See http://www.kallisti.net.nz/EMusicJ/InstallingJava for details.
      exit 1
    else
      return 0
    fi
  else
    echo You don\'t seem to have a valid JRE "[java = ${JAVA_IMPL}]" 
    echo See http://www.kallisti.net.nz/EMusicJ/InstallingJava for details.
    exit 1
  fi
}


if [ -z "$PROGRAM_DIR" ]; then
  ## resolve links - $0 may be a link to eMusicJ's home
  PRG="$0"

  # need this for relative symlinks
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG="`dirname "$PRG"`/$link"
    fi
  done

  saveddir=`pwd`

  PROGRAM_DIR=`dirname "$PRG"`

  # make it fully qualified
  PROGRAM_DIR=`cd "$PROGRAM_DIR" && pwd`

  cd "$saveddir"
  echo Using passionato at $PROGRAM_DIR
else
    if [ "$(echo ${PROGRAM_DIR}/lib/*.jar)" = "${PROGRAM_DIR}/lib/*.jar" ]; then
        echo "You seem to have set an invalid PROGRAM_DIR, unable to continue!"
        exit 1
    elif ! (echo ${PROGRAM_DIR}/lib/*.jar | grep passionato.jar >/dev/null 2>&1 ); then
        echo "Unable to locate passionato.jar in $PROGRAM_DIR, aborting!"
        exit 1
    fi
fi
MACHINE=`uname -m`

check_version

# swt.jar is referenced twice because it is in a different place on a 
# checked-out tree versus a dist build
MY_CLASSPATH="${PROGRAM_DIR}/lib/${MACHINE}/swt.jar:${PROGRAM_DIR}/lib/swt.jar:${PROGRAM_DIR}/lib/commons-codec-1.3.jar:${PROGRAM_DIR}/lib/commons-httpclient-3.0-rc4.jar:${PROGRAM_DIR}/lib/commons-logging-api.jar:${PROGRAM_DIR}/lib/retroweaver-rt-1.2.4.jar:${PROGRAM_DIR}/lib/guice-1.0.jar:${PROGRAM_DIR}/lib/MRJAdapter.jar:${PROGRAM_DIR}/lib/JID3.jar:${PROGRAM_DIR}/lib/jaudiotagger-2.0.1.jar:$CLASSPATH"

if [ -e ${PROGRAM_DIR}/bin/nz/net/kallisti/emusicj/Passionato.class ] ; then
        java -cp "${PROGRAM_DIR}/bin:$MY_CLASSPATH" "-Djava.library.path=${PROGRAM_DIR}/lib/${MACHINE}" -Denv.http_proxy=${http_proxy} nz.net.kallisti.emusicj.Passionato "$@"
elif [ -e ${PROGRAM_DIR}/lib/passionato.jar ] ; then
	java -cp "${PROGRAM_DIR}/lib/passionato.jar:$MY_CLASSPATH" "-Djava.library.path=${PROGRAM_DIR}/lib" -Denv.http_proxy=${http_proxy} nz.net.kallisti.emusicj.Passionato "$@"
else
        echo "Couldn't find the compiled Java program.";
fi

